import android.appwidget.AppWidgetManager;
import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.widget.RemoteViews;

import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.sebi.app.R;
import com.sebi.app.widget.SebiWidgetLogic;
import com.sebi.app.widget.SebiWidgetProvider;
import com.sebi.app.widget.SebiWidgetStorageModule;

import org.json.JSONArray;
import org.json.JSONObject;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;

/**
 * Behavior tests for the SHIPPED native widget code, run on the JVM against
 * recording stubs (Gradle/device builds are unavailable in the authoring
 * environment). Input: a JSON file produced by scripts/verify-widget.js
 * containing a REAL queue generated by the compiled TypeScript engine plus
 * parity expectations — an end-to-end contract test between the JS queue
 * generator and the native consumer.
 */
public final class SebiWidgetNativeTest {

    private static int failures = 0;

    private static void check(String name, boolean ok, String detail) {
        if (ok) {
            System.out.println("PASS " + name);
        } else {
            failures++;
            System.out.println("FAIL " + name + (detail == null ? "" : " :: " + detail));
        }
    }

    private static void check(String name, boolean ok) { check(name, ok, null); }

    private static boolean inFallbacks(String text, List<String> fallbacks) {
        return text != null && fallbacks.contains(text);
    }

    private static int hourFor(String period) {
        if ("morning".equals(period)) return 8;
        if ("day".equals(period)) return 13;
        if ("evening".equals(period)) return 19;
        return 23;
    }

    public static void main(String[] args) throws Exception {
        String input = new String(Files.readAllBytes(Paths.get(args[0])), StandardCharsets.UTF_8);
        JSONObject spec = new JSONObject(input);

        String queueJson = spec.optString("queueJson", null);
        JSONArray fallbackArr = spec.optJSONArray("fallbackTexts");
        List<String> fallbacks = new java.util.ArrayList<>();
        for (int i = 0; i < fallbackArr.length(); i++) {
            fallbacks.add(fallbackArr.optJSONObject(i).optString("text", ""));
        }

        // ---- SebiWidgetLogic: corrupt / empty inputs never break, never blank ----
        for (String[] bad : new String[][] {
                {"null queue", null},
                {"empty string queue", ""},
                {"garbage queue", "not json at all"},
                {"object-not-array queue", "{\"a\":1}"},
                {"empty array queue", "[]"},
                {"invalid slots queue", "[{\"id\":\"x\"},42,\"str\"]"},
        }) {
            SebiWidgetLogic.RenderSpec s = SebiWidgetLogic.choose(bad[1], "2026-08-23", 13, 235);
            check(bad[0] + " -> fallback", s.usedFallback && inFallbacks(s.text, fallbacks)
                    && SebiWidgetLogic.FALLBACK_LABEL.equals(s.label) && s.smallSp > 0 && s.mediumSp > 0,
                    s.text);
        }

        // Fallback is deterministic and rotates across periods.
        SebiWidgetLogic.RenderSpec f1 = SebiWidgetLogic.choose(null, "2026-08-23", 8, 235);
        SebiWidgetLogic.RenderSpec f2 = SebiWidgetLogic.choose(null, "2026-08-23", 8, 235);
        SebiWidgetLogic.RenderSpec f3 = SebiWidgetLogic.choose(null, "2026-08-23", 13, 235);
        check("fallback deterministic within period", f1.text.equals(f2.text));
        check("fallback rotates across periods", !f1.text.equals(f3.text), f1.text);

        // FALLBACK_TEXTS exactly matches the corpus-verified list from JS.
        check("FALLBACK_TEXTS matches corpus-verified list",
                Arrays.asList(SebiWidgetLogic.FALLBACK_TEXTS).equals(fallbacks),
                Arrays.toString(SebiWidgetLogic.FALLBACK_TEXTS));

        // periodForHour parity with the TypeScript engine, all 24 hours.
        JSONArray periods = spec.optJSONArray("periodByHour");
        boolean periodParity = periods.length() == 24;
        for (int h = 0; h < periods.length(); h++) {
            String expected = periods.optJSONObject(h).optString("period", "?");
            if (!expected.equals(SebiWidgetLogic.periodForHour(h))) periodParity = false;
        }
        check("periodForHour parity with TS (24h)", periodParity);

        // tierForLength parity with the TypeScript lengthTier.
        JSONArray tiers = spec.optJSONArray("tierSamples");
        boolean tierParity = tiers.length() > 0;
        for (int i = 0; i < tiers.length(); i++) {
            JSONObject t = tiers.optJSONObject(i);
            int len = Integer.parseInt(t.optString("len", "0"));
            if (!t.optString("tier", "?").equals(SebiWidgetLogic.tierForLength(len))) tierParity = false;
        }
        check("tierForLength parity with TS lengthTier", tierParity);

        // Deterministic sp tiers per spec.
        check("small sp tiers 17/16/15/14.5",
                SebiWidgetLogic.smallSp("short") == 17f && SebiWidgetLogic.smallSp("mid") == 16f
                        && SebiWidgetLogic.smallSp("long") == 15f && SebiWidgetLogic.smallSp("xl") == 14.5f);
        check("medium sp tiers 20/19/18/17",
                SebiWidgetLogic.mediumSp("short") == 20f && SebiWidgetLogic.mediumSp("mid") == 19f
                        && SebiWidgetLogic.mediumSp("long") == 18f && SebiWidgetLogic.mediumSp("xl") == 17f);

        // Layout switch threshold (220dp), medium default when width unknown.
        check("layout threshold 220dp",
                !SebiWidgetLogic.useSmallLayout(0) && SebiWidgetLogic.useSmallLayout(1)
                        && SebiWidgetLogic.useSmallLayout(150) && SebiWidgetLogic.useSmallLayout(219)
                        && !SebiWidgetLogic.useSmallLayout(220) && !SebiWidgetLogic.useSmallLayout(320));

        // ---- Real queue (generated by the compiled TS engine) ----
        List<SebiWidgetLogic.Slot> slots = SebiWidgetLogic.parseQueue(queueJson);
        check("real queue parses fully", slots.size() >= 28, "slots=" + slots.size());

        JSONArray expectations = spec.optJSONArray("expectations");
        boolean allMatch = expectations.length() > 0;
        String mismatch = null;
        for (int i = 0; i < expectations.length(); i++) {
            JSONObject e = expectations.optJSONObject(i);
            String date = e.optString("date", "");
            String period = e.optString("period", "");
            String expectedId = e.optString("expectedId", "");
            SebiWidgetLogic.RenderSpec s =
                    SebiWidgetLogic.choose(queueJson, date, hourFor(period), 100);
            if (!expectedId.equals(s.id) || s.usedFallback) {
                allMatch = false;
                mismatch = date + "/" + period + " -> " + s.id + " wanted " + expectedId;
            }
        }
        check("exact (date, period) slot matching", allMatch, mismatch);

        String lastId = spec.optString("lastQueueId", "");
        SebiWidgetLogic.RenderSpec stale = SebiWidgetLogic.choose(queueJson, "2099-12-31", 13, 100);
        check("stale queue degrades to latest past slot", lastId.equals(stale.id) && !stale.usedFallback,
                stale.id);

        String firstId = spec.optString("firstQueueId", "");
        SebiWidgetLogic.RenderSpec future = SebiWidgetLogic.choose(queueJson, "2000-01-01", 13, 5);
        check("future-only queue shows first slot", firstId.equals(future.id) && !future.usedFallback,
                future.id);

        // Partially corrupt queue keeps valid slots.
        String half = "[{\"id\":\"a\",\"text\":\"Tekst poruke.\",\"label\":\"ZA DANAS\","
                + "\"period\":\"day\",\"date\":\"2026-08-23\",\"tier\":\"short\"},"
                + "{\"id\":\"\"},{\"bad\":true},17]";
        check("partially corrupt queue keeps valid slots", SebiWidgetLogic.parseQueue(half).size() == 1);

        // Unknown tier falls back to length-derived sizing.
        String weird = "[{\"id\":\"a\",\"text\":\"Tekst poruke.\",\"label\":\"ZA DANAS\","
                + "\"period\":\"day\",\"date\":\"2026-08-23\",\"tier\":\"weird\"}]";
        SebiWidgetLogic.RenderSpec ws = SebiWidgetLogic.choose(weird, "2026-08-23", 13, 1);
        check("unknown tier derives size from length", ws.smallSp == 17f && ws.mediumSp == 20f);

        // ---- SebiWidgetProvider over recording stubs ----
        AppWidgetManager mgr = new AppWidgetManager();
        AppWidgetManager.instance = mgr;
        Context ctx = new Context();
        ctx.sharedPreferences = new SharedPreferences();

        // Empty storage: renders a built-in fallback, never blank, never brand-only.
        SebiWidgetProvider provider = new SebiWidgetProvider();
        provider.onUpdate(ctx, mgr, new int[] {1});
        RemoteViews empty = mgr.lastViews.get(1);
        check("provider empty storage -> fallback quote",
                empty != null && inFallbacks(String.valueOf(empty.texts.get(R.id.sebi_widget_quote)), fallbacks));
        check("provider empty storage -> ZA DANAS label",
                empty != null && "ZA DANAS".equals(String.valueOf(empty.texts.get(R.id.sebi_widget_label))));
        check("provider default layout is medium", empty != null && empty.layoutId == R.layout.sebi_widget_medium);
        check("provider sets time-of-day background", empty != null
                && empty.backgroundResources.containsKey(R.id.sebi_widget_root));
        check("provider sets TalkBack description 'Sebi. <text>'", empty != null
                && String.valueOf(empty.contentDescriptions.get(R.id.sebi_widget_root)).startsWith("Sebi. "));
        check("provider sets tap-to-open PendingIntent", empty != null
                && empty.clickIntents.containsKey(R.id.sebi_widget_root));

        // Resize: small below 220dp, medium at/above.
        Bundle smallOpts = new Bundle();
        smallOpts.putInt(AppWidgetManager.OPTION_APPWIDGET_MIN_WIDTH, 150);
        mgr.options.put(1, smallOpts);
        provider.onAppWidgetOptionsChanged(ctx, mgr, 1, smallOpts);
        check("resize to 150dp -> small layout", mgr.lastViews.get(1).layoutId == R.layout.sebi_widget_small);
        Bundle medOpts = new Bundle();
        medOpts.putInt(AppWidgetManager.OPTION_APPWIDGET_MIN_WIDTH, 320);
        mgr.options.put(1, medOpts);
        provider.onAppWidgetOptionsChanged(ctx, mgr, 1, medOpts);
        check("resize to 320dp -> medium layout", mgr.lastViews.get(1).layoutId == R.layout.sebi_widget_medium);

        // Populated queue: rendered text agrees with the logic layer for "now".
        ctx.sharedPreferences.values.put("queue_json", queueJson);
        provider.onUpdate(ctx, mgr, new int[] {1});
        Calendar now = Calendar.getInstance();
        String today = String.format(Locale.US, "%04d-%02d-%02d",
                now.get(Calendar.YEAR), now.get(Calendar.MONTH) + 1, now.get(Calendar.DAY_OF_MONTH));
        SebiWidgetLogic.RenderSpec expectedNow = SebiWidgetLogic.choose(
                queueJson, today, now.get(Calendar.HOUR_OF_DAY), now.get(Calendar.DAY_OF_YEAR));
        RemoteViews populated = mgr.lastViews.get(1);
        check("provider renders current queue slot",
                expectedNow.text.equals(String.valueOf(populated.texts.get(R.id.sebi_widget_quote)))
                        && !expectedNow.usedFallback,
                String.valueOf(populated.texts.get(R.id.sebi_widget_quote)));
        check("provider sets quote size in sp",
                populated.textSizesSp.get(R.id.sebi_widget_quote) != null
                        && populated.textSizesSp.get(R.id.sebi_widget_quote) >= 14.5f);
        check("provider persists rotation state",
                ctx.sharedPreferences.values.get("last_slot_key") != null);

        // Corrupt stored queue: no crash, fallback rendered.
        ctx.sharedPreferences.values.put("queue_json", "###corrupt###");
        provider.onUpdate(ctx, mgr, new int[] {1});
        check("provider corrupt queue -> fallback, no crash",
                inFallbacks(String.valueOf(mgr.lastViews.get(1).texts.get(R.id.sebi_widget_quote)), fallbacks));

        // renderAll touches every placed widget.
        mgr.widgetIds = new int[] {1, 2};
        int before = mgr.updates.size();
        ctx.sharedPreferences.values.put("queue_json", queueJson);
        SebiWidgetStorageModule module = buildModule(ctx);
        Promise ok = new Promise();
        module.setQueue(queueJson, ok);
        check("module setQueue resolves with slot count", ok.settled && ok.resolved instanceof Integer
                && (Integer) ok.resolved >= 28, String.valueOf(ok.resolved));
        check("module setQueue stores queue + timestamp",
                queueJson.equals(ctx.sharedPreferences.values.get("queue_json"))
                        && ctx.sharedPreferences.values.get("generated_at") != null);
        check("module setQueue re-renders all placed widgets", mgr.updates.size() >= before + 2,
                (mgr.updates.size() - before) + " updates");

        Promise emptyPromise = new Promise();
        module.setQueue("[]", emptyPromise);
        check("module rejects empty queue", "E_EMPTY_QUEUE".equals(emptyPromise.rejectCode));
        Promise nullPromise = new Promise();
        module.setQueue(null, nullPromise);
        check("module rejects null queue", "E_EMPTY_QUEUE".equals(nullPromise.rejectCode));

        ctx.sharedPreferences.commitResult = false;
        Promise failPromise = new Promise();
        module.setQueue(queueJson, failPromise);
        check("module surfaces failed writes", "E_WRITE_FAILED".equals(failPromise.rejectCode));
        ctx.sharedPreferences.commitResult = true;

        // ---- Deep link: widget tap carries the EXACT rendered affirmation ----
        String deepLinkFor = "sebi://danas?affirmationId=";
        mgr.widgetIds = new int[] {1};
        mgr.options.clear();
        ctx.sharedPreferences.values.put("queue_json", queueJson);
        provider.onUpdate(ctx, mgr, new int[] {1});
        Calendar dlNow = Calendar.getInstance();
        String dlToday = String.format(Locale.US, "%04d-%02d-%02d",
                dlNow.get(Calendar.YEAR), dlNow.get(Calendar.MONTH) + 1, dlNow.get(Calendar.DAY_OF_MONTH));
        SebiWidgetLogic.RenderSpec current = SebiWidgetLogic.choose(
                queueJson, dlToday, dlNow.get(Calendar.HOUR_OF_DAY), dlNow.get(Calendar.DAY_OF_YEAR));
        String dataA = String.valueOf(
                mgr.lastViews.get(1).clickIntents.get(R.id.sebi_widget_root).intent.data);
        check("G: PendingIntent deep link carries the current slot id",
                dataA.equals(deepLinkFor + current.id), dataA + " wanted " + current.id);

        // H: rotation X -> Y updates the deep link, never a stale earlier id.
        String slotY = "[{\"id\":\"rotation_target\",\"text\":\"Nova poruka za rotaciju.\","
                + "\"label\":\"ZA DANAS\",\"period\":\"" + SebiWidgetLogic.periodForHour(dlNow.get(Calendar.HOUR_OF_DAY))
                + "\",\"date\":\"" + dlToday + "\",\"tier\":\"short\"}]";
        ctx.sharedPreferences.values.put("queue_json", slotY);
        provider.onUpdate(ctx, mgr, new int[] {1});
        String dataB = String.valueOf(
                mgr.lastViews.get(1).clickIntents.get(R.id.sebi_widget_root).intent.data);
        check("H: rotated widget deep-links to the NEW id, not the stale one",
                dataB.equals(deepLinkFor + "rotation_target") && !dataB.equals(dataA), dataB);

        // I: small and medium layouts carry the same current id.
        Bundle smallDl = new Bundle();
        smallDl.putInt(AppWidgetManager.OPTION_APPWIDGET_MIN_WIDTH, 150);
        mgr.options.put(1, smallDl);
        provider.onUpdate(ctx, mgr, new int[] {1});
        String dataSmall = String.valueOf(
                mgr.lastViews.get(1).clickIntents.get(R.id.sebi_widget_root).intent.data);
        check("I: small and medium widgets deep-link the same current id",
                dataSmall.equals(dataB)
                        && mgr.lastViews.get(1).layoutId == R.layout.sebi_widget_small);
        mgr.options.clear();

        // J: bundled fallback carries its REAL corpus id.
        ctx.sharedPreferences.values.remove("queue_json");
        provider.onUpdate(ctx, mgr, new int[] {1});
        String dataFallback = String.valueOf(
                mgr.lastViews.get(1).clickIntents.get(R.id.sebi_widget_root).intent.data);
        boolean fallbackIdReal = false;
        for (String id : SebiWidgetLogic.FALLBACK_IDS) {
            if (dataFallback.equals(deepLinkFor + id)) fallbackIdReal = true;
        }
        check("J: fallback tap deep-links to a real corpus id", fallbackIdReal, dataFallback);
        check("fallback ids never use synthetic fallback_ prefixes",
                !String.join(",", SebiWidgetLogic.FALLBACK_IDS).contains("fallback_"));
        check("fallback ids and texts stay aligned",
                SebiWidgetLogic.FALLBACK_IDS.length == SebiWidgetLogic.FALLBACK_TEXTS.length);

        // Deep-link intent shape: explicit package, VIEW action, safe flags.
        android.content.Intent tapIntent =
                mgr.lastViews.get(1).clickIntents.get(R.id.sebi_widget_root).intent;
        check("deep-link intent targets our package with ACTION_VIEW",
                "com.sebi.app".equals(tapIntent.packageName)
                        && android.content.Intent.ACTION_VIEW.equals(tapIntent.action));
        check("deep-link PendingIntent uses UPDATE_CURRENT | IMMUTABLE",
                (mgr.lastViews.get(1).clickIntents.get(R.id.sebi_widget_root).flags
                        & (android.app.PendingIntent.FLAG_UPDATE_CURRENT | android.app.PendingIntent.FLAG_IMMUTABLE))
                        == (android.app.PendingIntent.FLAG_UPDATE_CURRENT | android.app.PendingIntent.FLAG_IMMUTABLE));

        System.out.println(failures == 0 ? "NATIVE_TESTS_PASSED" : "NATIVE_TESTS_FAILED " + failures);
        System.exit(failures == 0 ? 0 : 1);
    }

    private static SebiWidgetStorageModule buildModule(Context ctx) {
        ReactApplicationContext reactCtx = new ReactApplicationContext();
        reactCtx.sharedPreferences = ctx.sharedPreferences;
        reactCtx.packageManager = ctx.packageManager;
        return new SebiWidgetStorageModule(reactCtx);
    }
}
